shellchecked cli structure

diff --git a/denv b/denv
--- a/denv
+++ b/denv
@@ -67,7 +67,7 @@ _denv_deduce_workspace() {
     if [ -d "${denv_workspace}/.denv" ]; then
       return 0
     fi
-    denv_workspace="$(dirname ${denv_workspace} || true)"
+    denv_workspace="$(dirname "${denv_workspace}" || true)"
   done
   echo "ERROR: Unable to deduce a denv workspace!"
   echo "       Are you in a denv workspace? Do you still need to 'denv init'?"
@@ -80,7 +80,9 @@ _denv_deduce_workspace() {
 # Outputs
 #  loaded config into runtime shell environment
 _denv_load_config() {
-  . "${denv_workspace}"/.denv/config
+  # I am choosing to allow sourcing unknown code
+  # shellcheck disable=SC1091
+  . "${denv_workspace}/.denv/config"
 }
 
 # write the current config to the file
@@ -89,10 +91,12 @@ _denv_load_config() {
 #  env - config variables from runtime env
 _denv_write_config() {
   config="${denv_workspace}/.denv/config"
-  echo "denv_home=\"${denv_home}\"" > "${config}"
-  echo "denv_image=\"${denv_image}\"" >> "${config}"
-  echo "denv_shell=\"${denv_shell}\"" >> "${config}"
-  echo "denv_mounts=\"${denv_mounts}\"" >> "${config}"
+  { 
+    echo "denv_home=\"${denv_home}\"";
+    echo "denv_image=\"${denv_image}\"";
+    echo "denv_shell=\"${denv_shell}\"";
+    echo "denv_mounts=\"${denv_mounts}\"";
+  } > "${config}"
 }
 
 # edit the home directory of the denv
@@ -113,8 +117,23 @@ _denv_edit_home() {
 #  1 - new image for the denv
 _denv_edit_image() {
   denv_image="$1"
+  # I do want to fail-quiet here and so I implicitly
+  # disable the 'set -e' flag which would normally
+  # exit the program with any non-zero exit status
+  # shellcheck disable=SC2310
   if ! _denv_image_exists; then
     _denv_pull
+  else
+    printf "%s already exists on this computer - re-pull it? [Y/n] " "${denv_image}"
+    read -r ans
+    case "${ans}" in
+      Y|y)
+        _denv_pull
+        ;;
+      *)
+        echo "Not pulling ${denv_image}..."
+        ;;
+    esac
   fi
 }
 
@@ -129,7 +148,6 @@ _denv_edit_shell() {
 # Arguments
 #  1 - path to directory to mount to container
 _denv_edit_mounts() {
-  new_mount="$1"
   case "$1" in
     /*)
       # this is a full path
@@ -221,6 +239,8 @@ _denv_init() {
       _denv_init_help
       return 0
       ;;
+    *)
+      ;;
   esac
   # image - first positional and only required argument
   image="$1"
@@ -234,7 +254,8 @@ _denv_init() {
 
   # check if we already been init'ed
   if [ -d "${denv_workspace}/.denv" ];then
-    read -p "This workspace already has a denv. Would you like to overwrite it? [Y/n] " ans
+    printf "This workspace already has a denv. Would you like to overwrite it? [Y/n] "
+    read -r ans
     case "${ans}" in
       Y|y)
         # delete old denv and continue below
@@ -254,10 +275,37 @@ _denv_init() {
   denv_mounts=""
   mkdir "${denv_workspace}/.denv"
   _denv_write_config
+  cat > "${denv_workspace}/.denv/.gitignore" <<\GITIGNORE
+# ignore directory storing image files for some runners
+images/
+# ignore lock file signaling to the entrypoint script that
+# the home has already been initialized
+home-init-lock
+GITIGNORE
 
+  # I do want to fail-quiet here and so I implicitly
+  # disable the 'set -e' flag which would normally
+  # exit the program with any non-zero exit status
+  # shellcheck disable=SC2310
   if ! _denv_image_exists; then
     _denv_pull
+  else
+    printf "%s already exists on this computer - re-pull it? [Y/n] " "${denv_image}"
+    read -r ans
+    case "${ans}" in
+      Y|y)
+        _denv_pull
+        ;;
+      *)
+        echo "Not pulling ${denv_image}..."
+        ;;
+    esac
   fi
+}
+
+# print the denv version
+_denv_version() {
+  echo "denv v${denv_version}"
 }
 
 # root program denv
@@ -289,27 +337,29 @@ _denv() {
   fi
 
   case "$1" in
-    help|-h|--help)
+    -h|--help)
       _denv_help
-      return 0
+      return 
       ;;
-    edit)
+    version|help|edit|init)
+      cmd="_denv_${1}"
       shift
-      _denv_edit $@
-      return $?
-      ;;
-    init)
-      shift
-      _denv_init $@
+      # I think I know what I'm doing here
+      # shellcheck disable=SC2068
+      ${cmd} $@
       return $?
       ;;
     *)
       _denv_deduce_workspace
       _denv_load_config
+      # I think I know what I'm doing here
+      # shellcheck disable=SC2068
       _denv_run $@
       return $?
       ;;
   esac
 }
 
+# I think I know what I'm doing here
+# shellcheck disable=SC2068
 _denv $@
